---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  workflow_call:
    inputs:
      collection_namespace_1:
        description: First namespace to push to as in 'infra'
        required: true
        type: string
      collection_namespace_2:
        description: Second namespace like redhat_cop
        required: true
        type: string
      collection_name_1:
        description: "Path to the collection source"
        required: true
        type: string
      collection_name_2:
        description: "Path to the collection source"
        required: true
        type: string
      collection_repo:
        description: The collection url
        required: false
        type: string
      quay_username:
        description: "username/namespace to upload the EE to"
        required: true
        type: string
      collection_dependencies:
        description: The collection dependencies (as a space separated list)
        required: false
        type: string
      publish_url_collection_1:
        description: The url to publish to
        default: 'https://galaxy.ansible.com'
        required: false
        type: string
      publish_url_collection_2:
        description: The url to publish to
        default: 'https://galaxy.ansible.com'
        required: false
        type: string
      ah_publish_1:
        description: Publish the collection on automation hub
        default: false
        type: boolean
      ah_publish_2:
        description: Publish the collection on automation hub
        default: false
        type: boolean
      galaxy_publish_1:
        default: true
        description: Publish the collection on galaxy
        type: boolean
      galaxy_publish_2:
        default: true
        description: Publish the collection on galaxy
        type: boolean
      matrix_message:
        description: The additional message to send about the release.
        default: ''
        required: false
        type: string

    secrets:
      collection_api_key_1:
        description: API key for galaxy
        required: true
      collection_api_key_2:
        description: API key for galaxy
        required: true
      git_token:
        description: token for uploading tarballs to a release
        required: true
      quay_token:
        description: token for quay
        required: true
      matrix_token:
        description: token for quay
        required: true

jobs:

  calculate_version:
    name: Calculate Collection Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the most recent tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Checkout tooling repo
        uses: actions/checkout@v4
        with:
          repository: redhat-cop/ansible_collections_tooling
          path: ansible_collections_tooling

      - name: Calculate bump level
        id: bump_level
        shell: bash
        run: ansible_collections_tooling/.github/release/calculate_change.sh

      - name: Bump version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.bump_level.outputs.level }}
    outputs:
      collection_version: ${{ steps.bump-semver.outputs.new_version }}
      change_level: ${{ steps.bump_level.outputs.level }}
      change_present: ${{ steps.bump_level.outputs.change_present }}

  changelog:
    needs:
      - calculate_version
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/create_changelog_crc.yml@main
    with:
      collection_namespace: ${{ inputs.collection_namespace_1 }}
      collection_name: ${{ inputs.collection_name_1 }}
      collection_version: ${{ needs.calculate_version.outputs.collection_version }}
      collection_repo: ${{ inputs.collection_repo }}
    secrets:
      token: ${{ secrets.git_token }}
  merge_release:
    needs:
      - changelog
      - calculate_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/${{ needs.calculate_version.outputs.collection_version }}
      - name: Create Pull Request
        id: prcreate
        run: |
          gh pr create \
            --base devel \
            --head release/${{ needs.calculate_version.outputs.collection_version }} \
            --title '[RELEASE] Update changelog ${{ needs.calculate_version.outputs.collection_version }}' \
            --body 'Updated with changelog for release ${{ needs.calculate_version.outputs.collection_version }}' \
        env:
          GH_TOKEN: ${{ secrets.git_token }}
      - name: Merge PR
        run: gh pr merge "release/${{ needs.calculate_version.outputs.collection_version }}" --rebase --admin
        env:
          GH_TOKEN: ${{ secrets.git_token }}
...
